config/routes.rb
Rails.application.routes.draw do


  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources "sessions", only: [:show]

  root to: 'pages#home'
  get 'le-programme', to:'pages#program', as: 'program'
  get 'candidature', to: 'candidates#new', as: 'new_candidate'
  get 'code-vs-calanques', to: 'pages#code_vs_calanques'

  resources "candidates", only: [:create]

  resources "contacts", only: [:new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  belongs_to :session

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :session, presence: true

  after_create :send_welcome_email

  def send_welcome_email
    CandidateMailer.welcome(self).deliver_now
    AdminMailer.welcome(self).deliver_now
  end


end

app/models/session.rb
class Session < ApplicationRecord
  has_many :candidates, dependent: :destroy

  validates :size, presence: true
  validates :price, presence: true

  def to_param
    "#{self.id}-#{self.name.parameterize}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def default_url_options
    { host: ENV['HOST'] || 'localhost:3000' }
  end


end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController


  def new
    @candidate = Candidate.new
    @candidate.session_id = params[:session].to_i if params[:session]
    @session = Session.first
  end


  def create
    @candidate = Candidate.new(candidate_params)
    if @candidate.save
      redirect_to root_path, notice: "Merci, votre candidature a bien été prise en compte"
    else
      render :new
    end
  end


  def candidate_params
    params.require("candidate").permit(:last_name, :first_name, :email, :session_id)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
  end

  def create
    response = SubscribeToNewsletter.new(params[:email]).run
    render json: response
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @sessions = Session.all
  end

  def program
  end

  def code_vs_calanques
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def show
    @session = Session.find(params[:id])
    @candidate = Candidate.new
  end

  def candidate
    @session = Session.find(params[:id])
    @candidate = @session.candidates.build(candidate_params)
    if @candidate.save
      redirect_to session_path(@session), notice: "votre inscription à été prise en compte"
    else
      render :action => :show
    end
  end


  def candidate_params
    params.require("candidate").permit(:last_name, :first_name, :email)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META['meta_title']
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META['meta_description']
  end

  def meta_image
    content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META['meta_image']
  end

end

app/views/candidates/new.html.erb
<div class="container padded">


  <h1> Postulez à Code & Calanques </h1>
 <p>Postulez dès maintenant pour réserver votre place</p>


  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-push-8 col-sm-4">
        <div class="card-message">
          <h3>Ce séjour comprend:</h3>
          <ul>
            <li><p>Le logement</p></li>
            <li><p>6 jours de cours</p></li>
            <li><p>30 heures de cours</p></li>
            <li><p>Les transports sur place</p></li>
          </ul>
        </div>
      </div>
      <div class="col-xs-12 col-sm-pull-4 col-sm-8">
        <%= simple_form_for(@candidate) do |f| %>
          <%= f.input :first_name, label: t('first_name') %>
          <%= f.input :last_name, label: t('last_name') %>
          <%= f.input :email, label: t('email') %>
          <%= f.association :session, include_blank: false %>
          <p><b>Prix : <%= @session.price %>   € TTC </b> </p>

          <%= f.submit 'Je postule', class: "btn btn-cc btn-cc-blue" %>
        <% end %>
      </div>

      </div>



      </div>
    </div>
  </div>



</div>

app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

app/views/contacts/new.html.erb
<h1>Contacts#new</h1>
<p>Find me in app/views/contacts/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <title>Code & Calanques</title>
    <meta name="description" content="<%= meta_description %>">
    <%= favicon_link_tag 'favicon.png' %>

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= image_url(meta_image) %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <meta property="og:fb_admin" content="<%= DEFAULT_META[:fb_admin] %>">

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META[:twitter_account] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META[:twitter_account] %>">
    <meta name="twitter:image:src" content="<%= image_url(meta_image) %>">

    <!-- Google+ Schema.org markup -->
    <meta itemprop="name" content="<%= meta_title %>">
    <meta itemprop="description" content="<%= meta_description %>">
    <meta itemprop="image" content="<%= image_url(meta_image) %>">


    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= render 'shared/footer' %>
    <%= render 'shared/analytics' %>

  </body>
</html>

app/views/pages/_card-prof.html.erb
<div class="card-prof">
  <h3><%= "#{data['first_name'].capitalize} #{data['last_name'].capitalize} "%></h3>
    <%= image_tag data['image'], class:"avatar-xxl avatar-bordered" %>
    <p class="title"><%= data['title'] %></p>
        <ul class="list-inline">


      <%= link_to "https://www.linkedin.com/in/#{data['linkedin']}", target: "blank" do %>
        <li>
          <i class="fa fa-linkedin-square" aria-hidden="true"></i>
        </li>
      <% end %>

    </ul>
    <p><%= raw data['description'] %><p>

</div>

app/views/pages/code_vs_calanques.html.erb
<div class="padded">

  <div class="container">

    <h1>Code vs Calanques : le clash de l'été</h1>

    <p>Si vous aviez le choix entre <strong> apprendre à coder</strong> ou <strong>découvrir les calanques</strong>, que feriez-vous ?</p>
    <p>Ne répondez pas trop vite, le choix n'est pas si simble, suivez d'abord notre série <em> Code vs Calanques</em> pendant l'été.</p>
    <p> Et si vous avez toujours du mal à faire votre choix, ne vous en faites pas avec notre formation
    <%= link_to new_candidate_path do %>
      <strong>Code & Calanques</strong>
    <% end %>
    vous pourrez faire les deux en même temps.</p>

    <div class="illustrations">


      <% ILLUSTRATIONS.each_with_index do |picture, index| %>
      <div class="illustration padded-sm text-center">
         <h3><%= "#{index+1}" %>)  </h3>
         <%= image_tag "illustrations/#{picture['image']}", class: 'img-thumbnail', 'data-title': "CODE vs CALANQUES", alt: "#{picture['name']}"%>
         <p><%= picture['description']%> </p>
      </div>
      <% end %>
    </div>

    <%= render partial: 'shared/share_this' %>

  </div>




</div>

app/views/pages/home.html.erb
<!-- Banner -->
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(244,245,247,0.07) 0%, rgba(5,9,12,0.4) 50%), url('<%= asset_path "calanque_3.jpg" %>');">
  <div class="banner-content">


    <h1> <%= image_tag "logo_white.png", alt: "Code & Calanques", id: "logo-banner" %> </h1>
    <p>Une semaine pour apprendre à coder dans un cadre unique</p>
    <%= link_to "Je postule", new_candidate_path,  class: "btn   btn-cc btn-cc-white btn-lg " %>
  </div>
</div>


<!-- Le concept -->
<div class="padded-sm" id="concept">
  <div class="container">
    <h2><%= t 'calanque.concept' %></h2>
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <p><%= simple_format t 'concept.description' %></p>
      </div>
    </div>
  </div>
</div>





<!-- Le code -->
<div class="padded-sm" id="code">

  <div class="container">
    <h2><%= t 'code.title' %></h2>
    <div class="row">
      <div class="col-xs-12 col-sm-6">
      <%= simple_format t 'code.description' %>
      </div>
      <div class="col-xs-12 col-sm-4 col-sm-offset-2">
        <%= link_to t('code.cta'), program_path, class: "btn btn-cc btn-cc-blue"%>
      </div>
    </div>
  </div>

</div>

<div class="section" id="calanques" style="height: 300px; background-size:cover; background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0) 50%), url('<%= asset_path "calanque_5.jpg" %>');">

  </div>
</div>


<!-- Les calanques -->
<div class="padded" id="calanques">

  <div class="container">
    <h2><%= t 'calanque.title' %></h2>

    <div class="row">

      <div class="col-xs-12 col-sm-6">
        <p><%= simple_format t 'calanque.description' %></p>
      </div>
      <div class="col-xs-12 col-sm-4 col-sm-offset-2">
        <%= link_to t('code.cta'), program_path, class: "btn btn-cc btn-cc-blue"%>
      </div>
    </div>
  </div>

</div>



<!-- Les calanques -->



<!-- Le staff -->

<div class="padded" id="profs">
  <div class="container">
    <h2>Les Profs</h2>
    <div class="row">
      <% PROFS.each do |key, data| %>
        <div class="col-xs-12 col-sm-6 col-md-6">
        <%= render partial: 'card-prof', locals: {data: data} %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!-- Les prochaines sessions -->
<div id="sessions" class="padded">
  <div class="container">
    <h2> <%= t 'session.title' %></h2>
    <%= simple_format t 'session.description' %>
    <div class="row">
      <% @sessions.each do |session| %>
        <div class="col-xs-12 col-sm-6">

          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= image_url(session.image) %>);">
              <div class="card-category"><%= "Du #{l(session.start_date, format: :short)} au #{l(session.end_date, format: :short)}" %></div>
              <div class="card-description">
                  <h3><%= "#{session.name} - #{session.price} €" %></h3>
                  <p><%= session.description %></p>
              </div>
              <%=link_to "", new_candidate_path({session: session}), class:"card-link" %>
          </div>
        </div>
        <% end %>
    </div>
  </div>
</div>




<!-- Le Inscription -->
<div class="section-sm background-blue text-white" id='inscription'>
  <div class="container">
    <div class="row">
    <div class="text-center">
      <h2>Inscrivez-vous à notre newsletter</h2>
        <%= form_tag contacts_path, id:"subscribe-form", method: "post", remote: true, class: "form-inline"  do %>
        <div class="form-message">

        </div>
        <div class="form-group">
            <%= text_field_tag :email, nil, placeholder: "email", class: "input-lg form-control" %>
        </div>
        <%= submit_tag "Je m'inscris", class: "btn btn-cc btn-cc-white btn-lg" %>
      <% end %>

    </div>

    </div>
  </div>
</div>

app/views/pages/program.html.erb
<!-- Banner -->
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(244,245,247,0.07) 0%, rgba(5,9,12,0.4) 50%), url('<%= asset_path "calanque_3.jpg" %>');">
  <div class="banner-content">


    <h1> <%= t 'program.title' %> </h1>
    <p><%= t 'program.baseline' %></p>
    <%= link_to "Je postule", new_candidate_path,  class: "btn   btn-cc btn-cc-white btn-lg " %>
  </div>
</div>



<div class="padded container">
  <h2>Le programme de la semaine</h1>

    <p>Apprenez enfin à coder un produit de A à Z, en combinant le FrontEnd et le BackEnd, en utilisant les outils des startups modernes et en déployant votre site sur internet.</p>
    <p>Pendant une semaine nous coderons un clone de AirBnB et nous vous  offrons le cours en ligne <a href="https://ondemand.lewagon.org/tracks/debutez-avec-ruby-on-rails/go"> Découvrez Ruby on Rails</a> du Wagon </p>
    <p>A la fin de la semaine, vous saurez donc coder AirBnB et Product Hunt</p>
    <p>La classe non ? </p>
  </div>

</div>

<%= render partial: 'shared/candidate-banner' %>

<div class="padded container">
  <div class="padded-sm">
    <h3><%= t 'program.about.title' %></h2>
    <ul>
      <%  t('program.about.list').each do |data| %>
          <li> <%= simple_format data %> </li>
      <% end %>
    </ul>

  </div>




  <div class="padded-sm">
    <h3>Description d'une journée type</h2>
    <p>Une journée type se déroule de la façon suivante: </p>
    <div class="typical-day-detail">
    <ul>
      <li><p><b>9h-12h:</b> Cours du Matin</p> </li>
      <li><p><b>12h-13h30:</b> Déjeuner tous ensemble</p> </li>
      <li><p><b>13h30-16h30:</b> Cours de l'après midi</p></li>
      <li><p><b>16h30-17h:</b> Pause </p></li>
      <li><p><b>17h-19h30:</b> Activé dans les calanques </p></li>
    </ul>
      <p><i>En fonction des saisons et des activités, le cours du matin peut-être inversé avec l'activité du soir</i></p>
    </div>
  </div>

  </div>


  </div>
</div>

app/views/shared/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-79282665-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/shared/_candidate-banner.html.erb
  <% if @session %>
  <% params = {session: @session} %>
  <% else %>
  <% params = nil %>
  <% end%>

  <div class="padded-sm background-blue text-center text-white">
    <p>Pour obtenir le programme détaillé, postulez à une formation.</p>
    <%= link_to "Je postule", new_candidate_path(params) , class: "btn btn-cc btn-cc-white" %>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible alert-fixed" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible alert-fixed" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <p>Le Wagon Aix-Marseille - With love<i class="fa fa-heart red icon-padded" aria-hidden="true"></i> from Marseille</p>
  <%= image_tag "email.png", width: '189' %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
  <%= image_tag "logo_white.png", alt:'Code & Calanques' %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">



    <!-- Text link -->
    <%= link_to "Concept", root_path(anchor: 'concept'), class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Text link -->
    <%= link_to "Code", root_path(anchor: 'code'), class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Text link -->
    <%= link_to "Calanques", root_path(anchor: 'calanques'), class: "navbar-wagon-item navbar-wagon-link" %>

    <%= link_to "Profs", root_path(anchor: 'profs'), class: "navbar-wagon-item navbar-wagon-link" %>

    <%= link_to "Code vs Calanques", code_vs_calanques_path, class: "navbar-wagon-item navbar-wagon-link" %>


    <!-- Button (call-to-action) -->
    <%= link_to "JE POSTULE", new_candidate_path, class: "navbar-wagon-item navbar-wagon-button btn btn-cc btn-cc-white"%>
  </div>

</div>

app/views/shared/_share_this.erb
<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-578786777773da61"></script>